### ISSUE TITLE
How should we standardize config schema for files?

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/pathogen-repo-guide#26]
## Context
This issue was originally brought up in https://github.com/nextstrain/measles/pull/9#pullrequestreview-1819090281 and I wanted to document options and consensus on how we should standardize Nextstrain config schemas for files. This is specifically for discussing config files required for workflows such as reference.gb, exclude.txt, include.txt, etc. 

Historically, these files were provided at the [top of the Snakefile](https://github.com/nextstrain/measles/blob/a39398bc7970379de2c18d27cb6a938d8139d84f/Snakefile#L5-L13). The files are grouped together instead of within rule specific params because a [single file may be used by multiple rules](https://github.com/nextstrain/measles/pull/9#discussion_r1456113529). 

To make the files easily configurable, the [ncov workflow moved the files to the config YAML](https://github.com/nextstrain/ncov/commit/f8c44774a0766e3ca1e5e5b2a6024f59c87afe7a#diff-38df760413887d0cc4ee5707919e6390456a863d326f6080644cc3d9c72e4bba) under a top level `files` key. Other pathogen repos have taken similar paths of providing config files through the config YAML, but have varying schemas. mpox uses [top level file name keys](https://github.com/nextstrain/mpox/blob/5d3a2675b5f3c2c142d8d65dd8937f093e9110be/phylogenetic/config/mpxv/config.yaml#L1-L9) (i.e. drops the `files` key) and it also includes [rule specific file name keys](https://github.com/nextstrain/mpox/blob/5d3a2675b5f3c2c142d8d65dd8937f093e9110be/phylogenetic/config/mpxv/config.yaml#L19C1-L20):
```yaml
auspice_config: "config/mpxv/auspice_config.json"
include: "config/mpxv/include.txt"
reference: "config/reference.fasta"
...
filter:
    exclude: "config/exclude_accessions.txt"
```

rsv uses the [top level `files` key](https://github.com/nextstrain/rsv/blob/0c053250e0f76e368aa3ede84c2d5e38fe32ebb8/config/configfile.yaml#L28-L30) and [top level file name keys](https://github.com/nextstrain/rsv/blob/0c053250e0f76e368aa3ede84c2d5e38fe32ebb8/config/configfile.yaml#L7-L9)
```yaml
exclude: "config/outliers.txt"
description: "config/description.md"
...
files:
    color_schemes: "config/colors.tsv"
    auspice_config: "config/auspice_config.json"
```

## Open questions

1. Is providing config files through the config YAML still the way forward?
2. Do we want to standardize config file schemas across pathogens? Should this be decided per pathogen repo? 
3. If we do standardize config schemas, should it use the top level `files` key, top level file name keys, or rule specific file name keys? Are there other suggested schemas?

**Comment by joverlee521** [comment]
(1) I'm slightly wary of [Snakemake's different interpretations of relative paths](https://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-does-snakemake-interpret-relative-paths), but this should be okay as long as config files are always used as `inputs` and we use [hardcoded `workdir` directives](https://github.com/nextstrain/pathogen-repo-template/pull/16). 
(2) I don't think we can have a completely standardized schema across repos, but we can at least standardize the schema for the purpose of providing config files.
(3) Copying my previous [comment](https://github.com/nextstrain/measles/pull/9#discussion_r1456454811): Grouping files together makes sense if expected to be used multiple times. I also see the other side of it being confusing to need to edit configs for the `filter` rule under both `files` and `filter`. It's also not be immediately obvious looking at the config what rules use which files (unless you have [detailed docs like ncov](https://docs.nextstrain.org/projects/ncov/en/latest/reference/workflow-config-file.html#files)).

**Comment by joverlee521** [comment]
Copying over @jameshadfield 's relevant [comment](https://github.com/nextstrain/measles/pull/9#discussion_r1456481784):

> I have spent plenty of time following the strings to work out which rules use which files (mainly in ncov), and often finding a bunch of files no longer used by any rule. Docs are great, but from experience they inevitably fall out of sync. How about something like the following (or a variant thereof)?

```yaml
files:
  exclude: &files_exclude 'config/exclude_accessions.txt'
filter:
  exclude: *files_exclude
```
